
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.ai
{

public sealed partial class IsNotSet :  ai.KeyQueryOperator 
{
    public IsNotSet(ByteBuf _buf)  : base(_buf) 
    {
    }

    public IsNotSet()  : base() 
    {
    }

    public static IsNotSet DeserializeIsNotSet(ByteBuf _buf)
    {
        return new ai.IsNotSet(_buf);
    }


    public const int ID = 790736255;
    public override int GetTypeId() => ID;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        OnResolveFinish(_tables);
    }

    partial void OnResolveFinish(Dictionary<string, object> _tables);

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    }

}

