
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.ai
{

public sealed partial class UeWaitBlackboardTime :  ai.Task 
{
    public UeWaitBlackboardTime(ByteBuf _buf)  : base(_buf) 
    {
        BlackboardKey = _buf.ReadString();
    }

    public UeWaitBlackboardTime(int id, string node_name, System.Collections.Generic.List<ai.Decorator> decorators, System.Collections.Generic.List<ai.Service> services, bool ignore_restart_self, string blackboard_key )  : base(id,node_name,decorators,services,ignore_restart_self) 
    {
        this.BlackboardKey = blackboard_key;
    }

    public static UeWaitBlackboardTime DeserializeUeWaitBlackboardTime(ByteBuf _buf)
    {
        return new ai.UeWaitBlackboardTime(_buf);
    }

    public readonly string BlackboardKey;

    public const int ID = 1215378271;
    public override int GetTypeId() => ID;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        OnResolveFinish(_tables);
    }

    partial void OnResolveFinish(Dictionary<string, object> _tables);

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "NodeName:" + NodeName + ","
        + "Decorators:" + Bright.Common.StringUtil.CollectionToString(Decorators) + ","
        + "Services:" + Bright.Common.StringUtil.CollectionToString(Services) + ","
        + "IgnoreRestartSelf:" + IgnoreRestartSelf + ","
        + "BlackboardKey:" + BlackboardKey + ","
        + "}";
    }
    }

}

