
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.limit
{

public sealed partial class DailyLimit :  limit.DailyLimitBase 
{
    public DailyLimit(ByteBuf _buf)  : base(_buf) 
    {
        Num = _buf.ReadInt();
    }

    public static DailyLimit DeserializeDailyLimit(ByteBuf _buf)
    {
        return new limit.DailyLimit(_buf);
    }

    public int Num { get; private set; }

    public const int ID = 303235413;
    public override int GetTypeId() => ID;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Num:" + Num + ","
        + "}";
    }
    }

}
