
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.limit
{

public sealed partial class GroupCoolDown :  limit.LimitBase 
{
    public GroupCoolDown(ByteBuf _buf)  : base(_buf) 
    {
        GroupId = _buf.ReadInt();
        Duration = _buf.ReadInt();
    }

    public GroupCoolDown(int group_id, int duration )  : base() 
    {
        this.GroupId = group_id;
        this.Duration = duration;
    }

    public static GroupCoolDown DeserializeGroupCoolDown(ByteBuf _buf)
    {
        return new limit.GroupCoolDown(_buf);
    }

    public readonly int GroupId;
    public readonly int Duration;

    public const int ID = 394328599;
    public override int GetTypeId() => ID;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        OnResolveFinish(_tables);
    }

    partial void OnResolveFinish(Dictionary<string, object> _tables);

    public override string ToString()
    {
        return "{ "
        + "GroupId:" + GroupId + ","
        + "Duration:" + Duration + ","
        + "}";
    }
    }

}

