
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.common
{

public sealed partial class DateTimeRange :  Bright.Config.BeanBase 
{
    public DateTimeRange(ByteBuf _buf) 
    {
        if(_buf.ReadBool()){ StartTime = _buf.ReadInt(); } else { StartTime = null; }
        if(_buf.ReadBool()){ EndTime = _buf.ReadInt(); } else { EndTime = null; }
    }

    public static DateTimeRange DeserializeDateTimeRange(ByteBuf _buf)
    {
        return new common.DateTimeRange(_buf);
    }

    public int? StartTime {get; private set;}
    public int? EndTime {get; private set;}

    public const int ID = 1642200959;
    public override int GetTypeId() => ID;

    public  void Resolve(Dictionary<string, object> _tables)
    {
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "StartTime:" + StartTime + ","
        + "EndTime:" + EndTime + ","
        + "}";
    }
    }

}
