return {
    id = 1020100001,
    name = "初始发型",
    major_type = '服装',
    minor_type = '发型',
    max_pile_num = 1,
    quality = '白',
    icon = "/Game/UI/UIText/IocnResource/Frames/S0012H_png.S0012H_png",
    icon_backgroud = "",
    icon_mask = "",
    desc = "初始发型",
    show_order = 6,
    quantifier = "套",
    show_in_bag = true,
    min_show_level = 5,
    batch_usable = true,
    progress_time_when_use = 1,
    show_hint_when_use = false,
    droppable = false,
    use_type = '手动',
}