return {
    id = 1022490000,
    name = "测试数据-包子",
    major_type = 4,
    minor_type = 403,
    max_pile_num = 100,
    quality = 2,
    icon = "/Game/UI/UIText/UI_TestIcon_1.UI_TestIcon_1",
    icon_backgroud = "",
    icon_mask = "",
    desc = "包子",
    show_order = 29,
    quantifier = "个",
    show_in_bag = true,
    min_show_level = 5,
    batch_usable = true,
    progress_time_when_use = 1,
    show_hint_when_use = false,
    droppable = true,
    use_type = 1,
}