return {
    id = 2,
    name = "金币",
    major_type = '货币',
    minor_type = '金币',
    max_pile_num = 9999999,
    quality = '白',
    icon = "/Game/UI/UIText/UI_TestIcon_1.UI_TestIcon_1",
    icon_backgroud = "",
    icon_mask = "",
    desc = "主要的高级流通代币",
    show_order = 2,
    quantifier = "个",
    show_in_bag = true,
    min_show_level = 5,
    batch_usable = true,
    progress_time_when_use = 1,
    show_hint_when_use = false,
    droppable = false,
    use_type = '手动',
}