return {
    id = 4,
    name = "经验",
    major_type = '货币',
    minor_type = '经验',
    max_pile_num = 9999999,
    quality = '白',
    icon = "/Game/UI/UIText/UI_TestIcon_1.UI_TestIcon_1",
    icon_backgroud = "",
    icon_mask = "",
    desc = "人物升级需要的经验",
    show_order = 4,
    quantifier = "点",
    show_in_bag = true,
    min_show_level = 5,
    batch_usable = true,
    progress_time_when_use = 1,
    show_hint_when_use = false,
    droppable = false,
    use_type = '手动',
}