<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="data\**" />
    <Compile Remove="pb_schemas\**" />
    <Compile Remove="schemas\**" />
    <EmbeddedResource Remove="data\**" />
    <EmbeddedResource Remove="pb_schemas\**" />
    <EmbeddedResource Remove="schemas\**" />
    <None Remove="data\**" />
    <None Remove="pb_schemas\**" />
    <None Remove="schemas\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove=".cache.meta" />
    <None Remove="gen_code_json.bat" />
    <None Remove="gen_pb.bat" />
    <None Remove="gen_platbuffers_code.bat" />
    <None Remove="gen_platbuffers_schema_data.bat" />
  </ItemGroup>

</Project>
